---
- name: Configure web server and database
  hosts: all
  become: yes  # Ensures tasks are run with elevated privileges
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - net-tools
        - ufw

