
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Fetch EC2 instance info
      amazon.aws.ec2_instance_info:
        region: us-east-1
        filters:
          instance-state-name: running
          "tag:Name": 
            - webapp-server1
            - db-server1
            - BastionHost
      register: ec2_info

    - name: Create inventory file
      ansible.builtin.copy:
        dest: "ip-targets.ini"
        content: |
          [webservers]
          {% for instance in ec2_info.instances if instance.tags.Name == 'webapp-server1' %}
          {{ instance.public_ip_address }} ansible_user=ubuntu
          {% endfor %}

          [dbservers]
          {% for instance in ec2_info.instances if instance.tags.Name == 'db-server1' %}
          {{ instance.private_ip_address }} ansible_user=ubuntu ansible_ssh_common_args='-o ProxyCommand="ssh -i path/to/private/key -W %h:%p -q ubuntu@{{ (ec2_info.instances | selectattr('tags.Name', 'equalto', 'BastionHost') | map(attribute='public_ip_address') | list)[0] }}"'
          {% endfor %}